# ⚠️ PROPRIETARY PROJECT - NO PUBLIC FUNDING

# This is the OFFICIAL Faheemly platform.
# Unauthorized copies are not eligible for sponsorship.

# If you want to support Faheemly:
# 1. Use the official SaaS platform: https://faheemly.com
# 2. Contact us for enterprise licensing: licensing@faheemly.com
# 3. Partner with us: hello@faheemly.com

# Do NOT sponsor unauthorized forks or clones.

custom: ['https://faheemly.com/contact', 'mailto:hello@faheemly.com']
