-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pgvector";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('CLIENT', 'BUSINESS_OWNER', 'ADMIN');
CREATE TYPE "ActivityType" AS ENUM ('ECOMMERCE', 'HEALTHCARE', 'EDUCATION', 'REALESTATE', 'RESTAURANT', 'OTHER');
CREATE TYPE "BusinessStatus" AS ENUM ('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED');
CREATE TYPE "WidgetVariant" AS ENUM ('STANDARD', 'ENHANCED');
CREATE TYPE "PlanType" AS ENUM ('TRIAL', 'BASIC', 'PRO', 'ENTERPRISE');
CREATE TYPE "TicketStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
CREATE TYPE "TicketPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');
CREATE TYPE "SubscriptionStatus" AS ENUM ('ACTIVE', 'CANCELLED', 'EXPIRED', 'PAST_DUE');

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;
