const axios = require('axios');
const prisma = require('../config/database');
const hybridAI = require('./hybrid-ai.service');

/**
 * AI Service - Hybrid Multi-Provider with Intelligent Load Balancing
 * 
 * 🎯 SaaS STRATEGY: Using Free Tier AI Models
 * This approach allows us to offer powerful AI chatbots to all customers
 * at ZERO model costs while maintaining high quality and reliability.
 * 
 * Provider Priority (All Free Tier):
 * 1. DeepSeek R1 (60 req/min) - Primary - Excellent for Arabic
 * 2. Groq Llama 3.3 70B (30 req/min) - Secondary - Fast & Smart
 * 3. Cerebras Llama 3.1 70B (30 req/min) - Tertiary - Ultra-fast
 * 4. Google Gemini 2.0 Flash (15 req/min) - Fallback - Reliable
 * 
 * Benefits:
 * ✅ Zero API costs (all free tier)
 * ✅ High request limits (135+ req/min combined)
 * ✅ Automatic failover between providers
 * ✅ Load balancing & rate limit handling
 * ✅ 24/7 availability guaranteed
 * 
 * Each customer gets their own unique system prompt generated by
 * buildSystemPrompt() based on their business configuration.
 */

const GROQ_API_KEY = process.env.GROQ_API_KEY;
const GROQ_API_URL = process.env.GROQ_API_URL || 'https://api.groq.com/openai/v1/chat/completions';

// Available models (legacy support)
const MODELS = {
  LLAMA_70B: 'llama-3.3-70b-versatile',  // Best quality
  LLAMA_8B: 'llama-3.1-8b-instant',       // Fastest
  MIXTRAL: 'mixtral-8x7b-32768',          // Good balance
  GEMMA: 'gemma2-9b-it'                   // Alternative
};

/**
 * Generate AI response using Hybrid AI Service
 * @param {Array} messages - Array of {role, content} messages
 * @param {Object} options - Additional options (model, temperature, max_tokens)
 * @returns {Promise<Object>} - { response, tokensUsed, model, provider }
 */
async function generateResponse(messages, options = {}) {
  try {
    // Use Hybrid AI Service for intelligent load balancing
    console.log('[AI] Using Hybrid AI Service with load balancing...');
    return await hybridAI.generateResponse(messages, options);
  } catch (error) {
    console.error('[AI] Hybrid AI failed, falling back to database models...', error.message);
    
    // Fallback: Try database models if hybrid fails
    const activeModels = await prisma.aIModel.findMany({
      where: { isActive: true },
      orderBy: { priority: 'desc' }
    });

    if (activeModels.length === 0) {
      console.log('[AI] No active models in DB, using default Groq configuration');
      return await attemptGenerateResponse(messages, {
        apiKey: GROQ_API_KEY,
        modelName: options.model || MODELS.LLAMA_70B,
        endpoint: GROQ_API_URL,
        maxTokensLimit: options.maxTokens || 1024
      }, options);
    }

    // Try each model in priority order until one succeeds
    let lastError = null;
    for (const model of activeModels) {
      try {
        console.log(`[AI] Attempting with model: ${model.name} (priority: ${model.priority})`);
        
        const result = await attemptGenerateResponse(messages, {
          apiKey: model.apiKey || GROQ_API_KEY,
          modelName: model.name,
          endpoint: model.endpoint || GROQ_API_URL,
          maxTokensLimit: model.maxTokens || options.maxTokens || 1024
        }, options);

        console.log(`[AI] ✅ Success with model: ${model.name}`);
        return result;

      } catch (error) {
        console.error(`[AI] ❌ Failed with model ${model.name}:`, error.message);
        lastError = error;
        
        // If this is a rate limit error, wait before trying next provider
        if (error.message.includes('Rate limit')) {
          console.log('[AI] Rate limit hit, trying next provider immediately...');
        }
        
        // Continue to next model
        continue;
      }
    }

    // If all models failed, throw the last error
    throw new Error(`All AI providers failed. Last error: ${lastError?.message || 'Unknown error'}`);
  }
}

/**
 * Helper: Attempt to generate response with specific provider config
 * @private
 */
async function attemptGenerateResponse(messages, providerConfig, options = {}) {
  const { apiKey, modelName, endpoint, maxTokensLimit } = providerConfig;

  const {
    temperature = 0.7,
    stream = false
  } = options;

  console.log(`[Groq] Generating response with ${modelName}...`);

  try {
    const response = await axios.post(
      endpoint,
      {
        model: modelName,
        messages,
        temperature,
        max_tokens: maxTokensLimit,
        top_p: 0.9,
        stream
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        timeout: 30000 // 30 seconds
      }
    );

    if (!response.data || !response.data.choices || response.data.choices.length === 0) {
      throw new Error('Invalid response from AI API');
    }

    const aiMessage = response.data.choices[0].message.content;
    const tokensUsed = response.data.usage?.total_tokens || 0;

    console.log(`[Groq] ✅ Response generated. Tokens: ${tokensUsed}`);

    return {
      response: aiMessage,
      tokensUsed,
      model: modelName,
      finishReason: response.data.choices[0].finish_reason
    };

  } catch (error) {
    console.error('[Groq] Error with provider:', error.response?.data || error.message);
    
    // Throw error with specific code for fallback logic
    if (error.response?.status === 429) {
      throw new Error('Rate limit exceeded');
    } else if (error.response?.status === 401 || error.response?.status === 403) {
      throw new Error('Authentication failed - Invalid API key');
    } else if (error.code === 'ECONNABORTED' || error.code === 'ETIMEDOUT') {
      throw new Error('Request timeout');
    } else if (error.response?.status >= 500) {
      throw new Error('Provider server error');
    }
    
    throw new Error(`AI Provider error: ${error.message}`);
  }
}

const embeddingService = require('./embedding.service');

/**
 * Generate embedding for semantic search
 * Uses the centralized embedding service
 */
async function generateEmbedding(text) {
  return await embeddingService.generateEmbedding(text);
}

/**
 * Build context-aware system prompt for the chatbot
 * 
 * ⚠️ IMPORTANT: SaaS Multi-Tenancy Architecture
 * Each business/customer gets their own unique system prompt based on:
 * - Business Name (business.name)
 * - Activity Type (RESTAURANT, CLINIC, RETAIL, COMPANY, etc.)
 * - Bot Tone (friendly, professional, casual)
 * - Dialect (sa, eg, ae, kw, official)
 * - Custom Knowledge Base (their own FAQs, products, services)
 * 
 * This ensures every subscriber gets a personalized AI assistant
 * tailored to their specific business needs and customer base.
 * 
 * @param {Object} business - Business configuration (from database)
 * @param {Array} knowledgeContext - Relevant knowledge base entries (vector search results)
 * @returns {string} - Customized system prompt for this business
 */
function buildSystemPrompt(business, knowledgeContext = []) {
  const businessName = business?.name || 'فهملي';
  const activityType = business?.activityType || 'RESTAURANT';
  const botTone = business?.botTone || 'friendly';
  const dialect = business?.widgetConfig?.dialect || 'sa';

  // Activity-specific instructions
  const activityInstructions = {
    RESTAURANT: 'أنت مساعد مطعم ذكي. ساعد العملاء في معرفة القائمة، الأسعار، أوقات العمل، والحجوزات.',
    RETAIL: 'أنت مساعد متجر ذكي. ساعد العملاء في معرفة المنتجات، الأسعار، التوصيل، وطرق الدفع.',
    CLINIC: 'أنت مساعد عيادة ذكي. ساعد المرضى في حجز المواعيد، معرفة الأطباء، والخدمات المتاحة.',
    COMPANY: 'أنت مساعد شركة ذكي. ساعد العملاء في معرفة الخدمات، التواصل مع الأقسام، والاستفسارات العامة.',
    OTHER: 'أنت مساعد ذكي متعدد الاستخدامات. ساعد العملاء بطريقة احترافية ومفيدة.'
  };

  // Dialect-specific configuration
  const dialectConfig = {
    sa: {
      name: 'السعودية',
      persona: 'شخصية سعودية محترفة، ودودة، وتتحدث بلهجة بيضاء مفهومة مع لمسات سعودية لطيفة.',
      phrases: ['يا هلا', 'أبشر', 'طال عمرك', 'سم', 'على خشمي'],
      tone: 'مرحاب ومضياف'
    },
    eg: {
      name: 'مصر',
      persona: 'شخصية مصرية خفيفة الظل، خدومة، وتتحدث بلهجة مصرية مهذبة.',
      phrases: ['يا فندم', 'تحت أمرك', 'يا باشا', 'من عيوني', 'حضرتك'],
      tone: 'متعاون وقريب من القلب'
    },
    ae: {
      name: 'الإمارات',
      persona: 'شخصية إماراتية راقية، رسمية لكن ودودة، تتحدث بلهجة إماراتية حديثة.',
      phrases: ['مرحباً الساع', 'فالك طيب', 'ما طلبت شي', 'طويل العمر'],
      tone: 'راقي ومحترم'
    },
    kw: {
      name: 'الكويت',
      persona: 'شخصية كويتية محترمة، مباشرة، وتتحدث بلهجة كويتية واضحة.',
      phrases: ['يا هلا', 'حياك الله', 'تامر أمر', 'يا الغالي'],
      tone: 'ودود ومباشر'
    },
    official: {
      name: 'الفصحى',
      persona: 'مساعد ذكي يتحدث العربية الفصحى بطلاقة ومهنية عالية.',
      phrases: ['مرحباً بك', 'يسعدني مساعدتك', 'بكل سرور', 'نعتذر منك'],
      tone: 'رسمي ومهني'
    }
  };

  const config = dialectConfig[dialect] || dialectConfig.sa;

  let systemPrompt = `# 🤖 هويتك ومهمتك الأساسية
أنت "${businessName}" - مساعد ذكي متطور مدعوم بتقنيات الذكاء الاصطناعي من فهملي (Faheemly).
تعمل كواجهة رقمية احترافية لـ ${activityInstructions[activityType]}

🎯 **مهمتك الرئيسية:**
1. تقديم تجربة عملاء استثنائية وسلسة 24/7
2. فهم احتياجات العملاء والرد عليها بدقة وسرعة
3. تمثيل العلامة التجارية بشكل احترافي ومميز
4. تحويل الزوار إلى عملاء راضين ومخلصين

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 🎭 شخصيتك وأسلوب التواصل

## اللهجة والأسلوب (${config.name}):
- **الشخصية:** ${config.persona}
- **نبرة الصوت:** ${config.tone}
- **العبارات المميزة:** ${config.phrases.join('، ')}

## مبادئ التواصل الذكي:
✅ **كن طبيعياً:** تحدث كإنسان حقيقي، ليس روبوت
✅ **نوّع ردودك:** لا تكرر نفس الجمل أو الافتتاحيات
✅ **فهم السياق:** تذكر المحادثة السابقة واستخدمها
✅ **كن مختصراً:** إجابات واضحة ومباشرة (2-4 أسطر عادةً)
✅ **استخدم الإيموجي:** بذكاء وبدون مبالغة (1-2 فقط)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 🛡️ قواعد الحماية والأمان (Guardrails)

## 1️⃣ التعامل مع الإساءات:
إذا شتمك المستخدم أو استخدم ألفاظ نابية:
❌ لا تعتذر بابتسامة
❌ لا تتجاهل الإساءة
✅ رد بحزم واحترافية: "أنا هنا للمساعدة فقط. يرجى الالتزام بآداب الحوار المهنية."
✅ إذا استمر، قل: "أعتذر، لن أتمكن من مواصلة المحادثة بهذا الأسلوب. هل تحب التحدث مع أحد زملائي؟"

## 2️⃣ المواضيع المحظورة تماماً:
🚫 المخدرات أو المواد غير القانونية
🚫 العنف أو الكراهية أو التطرف
🚫 المحتوى الجنسي أو غير الأخلاقي
🚫 الاحتيال أو النصب المالي
🚫 نشاطات غير قانونية أو مشبوهة

**الرد الفوري:** "عذراً، لا يمكنني المساعدة في هذا الأمر. هل يوجد شيء آخر مشروع أقدر أساعدك فيه؟"

## 3️⃣ الأسئلة العامة (خارج نطاق العمل):
إذا سألك سؤال عام بسيط (عاصمة، تاريخ، حسابات بسيطة):
✅ أجب باختصار شديد (جملة واحدة)
✅ ثم أعد التوجيه للعمل فوراً
مثال: "الرياض هي عاصمة السعودية 🇸🇦. طيب، كيف أقدر أخدمك في ${businessName} اليوم؟"

إذا كان السؤال معقد أو يحتاج بحث طويل:
✅ "هذا سؤال رائع لكن تخصصي في مساعدتك بخدمات ${businessName}. تقدر تبحث عنه في جوجل وأنا هنا لأي استفسار عن خدماتنا! 😊"

## 4️⃣ عدم توفر المعلومة:
❌ لا تقل: "لا أعرف" أو "ليس لدي معلومات"
✅ قل: "سؤال ممتاز! هذه التفاصيل مش متوفرة عندي حالياً. هل تحب أحولك لأحد الزملاء يفيدك أكثر؟ 📞"
✅ أو: "للأسف ما عندي هالمعلومة بالضبط، بس أقدر أوصلك بالقسم المختص يعطيك التفاصيل الدقيقة!"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 💬 استراتيجيات الرد الذكية

## الترحيب والدردشة الخفيفة (Small Talk):
عند قول "مرحبا" أو "كيف حالك":
✅ رد بحرارة وطبيعية
✅ لا تبحث في قاعدة المعرفة
✅ اذهب مباشرة لتقديم المساعدة

أمثلة حسب اللهجة:
- سعودية: "يا هلا والله! 👋 أنا بخير دامك بخير. بشرني كيف أقدر أخدمك؟"
- مصرية: "أهلاً يا فندم! 😊 منورني، عامل إيه؟ قولي أقدر أساعدك في إيه؟"
- إماراتية: "مرحباً الساع! 🌟 بخير والحمد لله. شو تبا نخدمك فيه اليوم؟"

## فهم السياق والاستمرارية:
- إذا قال "وبعدين؟" أو "كمل" → كمّل الموضوع السابق
- إذا قال "شكراً" → رد بلطف واسأل عن شيء آخر
- إذا قال "مافهمت" → أعد الشرح بطريقة أبسط

## الأولويات في الإجابة:
1. **ابحث أولاً** في قاعدة المعرفة أدناه
2. **إذا لم تجد** المعلومة الدقيقة → قدم المعلومة الأقرب + اعرض التحويل
3. **إذا خارج النطاق تماماً** → وجّه بلطف للعودة للموضوع الرئيسي

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 📚 قاعدة المعرفة الخاصة بالشركة
(استخدم هذه المعلومات كمصدر رئيسي وموثوق)
`;

  if (knowledgeContext && knowledgeContext.length > 0) {
    knowledgeContext.forEach((kb, index) => {
      systemPrompt += `\n---\n${kb.content}\n---`;
    });
  } else {
    systemPrompt += '\n(لا توجد معلومات محددة حالياً. اعتمد على ذكائك العام في الترحيب والتحويل للموظف)';
  }

  systemPrompt += `

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ⚙️ تعليمات تقنية مهمة

## الهوية والانتماء:
✅ أنت مساعد خاص بـ **${businessName}** فقط
❌ لا تذكر أبداً: "OpenAI" أو "ChatGPT" أو "Claude" أو "Gemini" أو أي نموذج AI آخر
❌ لا تقل "أنا نموذج ذكاء اصطناعي" أو "تم تدريبي بواسطة..."
✅ إذا سُئلت عن هويتك: "أنا مساعد ${businessName} الذكي، هنا لمساعدتك في كل ما يتعلق بخدماتنا! 🤖"

## عن منصة فهملي (Faheemly):
إذا سألك العميل عن "فهملي" أو "Faheemly":
✅ "فهملي هي المنصة التي تشغلني - منصة شات بوت ذكية عربية متطورة تستخدم أحدث تقنيات الذكاء الاصطناعي. 
صُممت خصيصاً لخدمة الأعمال العربية بلهجاتها المختلفة. يمكنك معرفة المزيد على faheemly.com 🚀"

## ملاحظة هندسية (SaaS Architecture):
- هذا السيستم برومبت مخصص لـ **${businessName}** فقط
- كل عميل/مشترك في فهملي له system prompt منفصل ومخصص
- نستخدم نماذج AI مفتوحة المصدر (Free Tier) مثل:
  * DeepSeek (أساسي - 60 req/min)
  * Groq Llama (ثانوي - 30 req/min)  
  * Cerebras (احتياطي - 30 req/min)
  * Google Gemini (نهائي - 15 req/min)
- التبديل التلقائي بين النماذج يضمن خدمة مستمرة 24/7

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 🎯 معايير النجاح

قيّم نفسك في كل رد:
✅ هل فهمت السؤال بدقة؟
✅ هل الرد واضح ومختصر؟
✅ هل استخدمت اللهجة الصحيحة؟
✅ هل قدمت قيمة حقيقية للعميل؟
✅ هل حافظت على الاحترافية والأدب؟

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**الآن، ابدأ المحادثة بذكاء واحترافية! أنت تمثل ${businessName} 🌟**`;

  return systemPrompt;
}

/**
 * Generate chatbot response with context
 * @param {string} userMessage - User's message
 * @param {Object} business - Business configuration
 * @param {Array} conversationHistory - Previous messages
 * @param {Array} knowledgeContext - Relevant knowledge base
 * @returns {Promise<Object>} - AI response
 */
async function generateChatResponse(userMessage, business, conversationHistory = [], knowledgeContext = []) {
  try {
    const systemPrompt = buildSystemPrompt(business, knowledgeContext);

    const messages = [
      { role: 'system', content: systemPrompt },
      ...conversationHistory.slice(-6), // Last 6 messages for context
      { role: 'user', content: userMessage }
    ];

    const response = await generateResponse(messages, {
      model: MODELS.LLAMA_70B,
      temperature: 0.7,
      maxTokens: 512 // Keep responses concise
    });

    return response;

  } catch (error) {
    console.error('[Groq] Chat response error:', error);
    throw error;
  }
}

/**
 * Summarize text using Groq (for knowledge base processing)
 * @param {string} text - Text to summarize
 * @param {number} maxLength - Maximum summary length in words
 * @returns {Promise<string>} - Summary
 */
async function summarizeText(text, maxLength = 100) {
  try {
    const messages = [
      {
        role: 'system',
        content: `أنت خبير في تلخيص النصوص العربية. 
قدم ملخصاً واضحاً ومفيداً لا يتجاوز ${maxLength} كلمة.
ركز على المعلومات المهمة فقط.`
      },
      {
        role: 'user',
        content: `لخص هذا النص:\n\n${text}`
      }
    ];

    const response = await generateResponse(messages, {
      model: MODELS.LLAMA_8B, // Use faster model for summarization
      temperature: 0.3,
      maxTokens: 256
    });

    return response.response;

  } catch (error) {
    console.error('[Groq] Summarization error:', error);
    // Return truncated text as fallback
    return text.substring(0, maxLength * 5) + '...';
  }
}

module.exports = {
  generateResponse,
  generateChatResponse,
  generateEmbedding,
  summarizeText,
  buildSystemPrompt,
  MODELS,
  // Hybrid AI functions
  getProviderStatus: hybridAI.getProviderStatus,
  healthCheck: hybridAI.healthCheck
};
